### ISSUE TITLE
libavcodec/avcodec.h: No such file or directory

### ISSUE THREAD

**Issue by maximeloridan** [youtube/yt-watchme#11]
Hi,

When I try to generate the apk, I have the error "libavcodec/avcodec.h: No such file or directory". 

I have done what is discribed in
http://www.roman10.net/how-to-build-ffmpeg-with-ndk-r9. So I did all this link said, and now, I have a folder /ffmpeg-2.4.3/android, which contains arm/lib and arm/include folders.

I tried to put these 2 folders in src/main/jni folder (where Android.mk and ffmeg.jni are), but still got the error.

Thank you very much

(I know that I have already asked a similar question in the other threads, and I apologize for that, I do not want to bother all of you)

**Comment by achinverma** [comment]
hi, i need help to solve this error https://github.com/youtube/yt-watchme/issues/35
