### ISSUE TITLE
ffmpeg-jni.c - Format not a string literal and no format arguments

### ISSUE THREAD

**Issue by ckarthikv** [youtube/yt-watchme#13]
jni/ffmpeg-jni.c: In function 'log_callback':
jni/ffmpeg-jni.c:84:3: error: format not a string literal and no format arguments [-Werror=format-security]
.
.
.
cc1: some warnings being treated as errors

make: **\* [obj/local/armeabi/objs/ffmpeg/ffmpeg-jni.o] Error 1

There seems to be some issue with the log_callback function in ffmpeg-jni.c? Pls help.

**Comment by ProFive** [comment]
Me, too. Please help find the issuss?

**Comment by achinverma** [comment]
hi, i need help to solve this error https://github.com/youtube/yt-watchme/issues/35
