### ISSUE TITLE
make: *** No rule to make target jni/../third_party/lame/libmp3lame/VbrTag.c'

### ISSUE THREAD

**Issue by ckarthikv** [youtube/yt-watchme#14]
make: **\* No rule to make target jni/../third_party/lame/libmp3lame/VbrTag.c', needed byobj/local/armeabi/objs/lame/VbrTag.o'. Stop.

How to get around this? Pls help. Thanks.

**Comment by danman81** [comment]
hi there -- if you were able to get this fixed, please do let us know, i am seeing the same thing!

**Comment by garyjamessilva** [comment]
http://stackoverflow.com/questions/8632835/lame-mp3-encoder-compile-for-android

**Comment by danman81** [comment]
thanks, garyjamessilva!  those bloody libraries!

**Comment by achinverma** [comment]
hi, i need help to solve this error https://github.com/youtube/yt-watchme/issues/35
