### ISSUE TITLE
src/main/jni/libavutil/float_dsp.h:148:50: error: expected ';', ',' or ')' before 'v1'

### ISSUE THREAD

**Issue by ckarthikv** [youtube/yt-watchme#15]
Built ffmpeg, ran the ndk, updated JNI codes, and on finally compiling, the following error comes up -

src/main/jni/libavutil/float_dsp.h:148:50: error: expected ';', ',' or ')' before 'v1'
    make: **\* [.../AndroidstudioProjects/yt-watchme-master/app/build/intermediates/ndk/debug/obj/local/armeabi-v7a/objs/app//Users/Karthik/AndroidstudioProjects/yt-watchme-master/app/src/main/jni/libavutil/arm/float_dsp_init_arm.o] Error 1

Have been stuck on this problem for ages. Help would be greatly appreciated.

**Comment by danman81** [comment]
i love you

**Comment by achinverma** [comment]
hi, i need help to solve this error https://github.com/youtube/yt-watchme/issues/35
