### ISSUE TITLE
youtube watchme error

### ISSUE THREAD

**Issue by abram456** [youtube/yt-watchme#44]
youtube watchme error:
- I'm able to connect to youtube 
- Its is asking to login with google
- Once I logged in, shows list of live events,
- On selecting event, it shows streaming window, then app is getting crashed (Unfortunately, youtube watch me has stopped working ).

This is the error I'm getting
"
10-27 11:24:56.096 30102-30102/com.google.android.apps.watchme E/art: No implementation found for boolean com.google.android.apps.watchme.Ffmpeg.init(int, int, int, java.lang.String) (tried Java_com_google_android_apps_watchme_Ffmpeg_init and Java_com_google_android_apps_watchme_Ffmpeg_init__IIILjava_lang_String_2)
10-27 11:24:56.101 30102-30102/com.google.android.apps.watchme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.google.android.apps.watchme, PID: 30102
                                                                                 java.lang.UnsatisfiedLinkError: No implementation found for boolean com.google.android.apps.watchme.Ffmpeg.init(int, int, int, java.lang.String) (tried Java_com_google_android_apps_watchme_Ffmpeg_init and Java_com_google_android_apps_watchme_Ffmpeg_init__IIILjava_lang_String_2)
                                                                                     at com.google.android.apps.watchme.Ffmpeg.init(Native Method)
"

**Comment by ghost** [comment]
post the answer
