### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by moonandroid** [youtube/yt-watchme#5]
I got this error ,when click on create event
Caused by: java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.<init>
Can i have list of supported jar for youtube live streaming so i can fix this issue?
Update here so i can fix this issue as soon as possible.

**Comment by achinverma** [comment]
hi, i need help to solve this error https://github.com/youtube/yt-watchme/issues/35
